//<editor-fold defaultstate="collapsed" desc="Copyright">
/*
 * Copyright (C) 2016 Błażej Sewera (Jazz)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//</editor-fold>
package mainPackage;

/**
 * @author Błażej Sewera (Jazz)
 * @version 0.5 (2016-05-13)
 */
public class ApplicationMainGUI extends javax.swing.JFrame {

    private final Amplituda amplituda;
    
    {
        amplituda = new Amplituda();
    }

    /**
     * Creates new form ApplicationMainGUI
     */
    public ApplicationMainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab13Segmentowa = new javax.swing.JTabbedPane();
        panel13Segmentowa = new javax.swing.JPanel();
        labelAmplituda0 = new javax.swing.JLabel();
        labelMaxAmplituda0 = new javax.swing.JLabel();
        textFieldAmplituda0 = new javax.swing.JTextField();
        textFieldMaxAmplituda0 = new javax.swing.JTextField();
        textFieldJednostkaAmplitudy0 = new javax.swing.JTextField();
        textFieldMaxJednostkaAmplitudy0 = new javax.swing.JTextField();
        labelJednostki0 = new javax.swing.JLabel();
        labelJednostki1 = new javax.swing.JLabel();
        textFieldWynik13Segmentowa = new javax.swing.JTextField();
        sliderAmplituda0 = new javax.swing.JSlider();
        sliderMaxAmplituda0 = new javax.swing.JSlider();
        labelWynik0 = new javax.swing.JLabel();
        buttonWystrzal13Segmentowa = new javax.swing.JButton();
        scrollPanePosrednie13Segmentowa = new javax.swing.JScrollPane();
        textAreaPosrednie13Segmentowa = new javax.swing.JTextArea();
        labelPosrednie0 = new javax.swing.JLabel();
        scrollPaneSegmenty13Segmentowa = new javax.swing.JScrollPane();
        listSegmenty13Segmentowa = new javax.swing.JList<>();
        labelSegment0 = new javax.swing.JLabel();
        panelCyfrowa = new javax.swing.JPanel();
        textFieldAmplituda1 = new javax.swing.JTextField();
        textFieldMaxAmplituda1 = new javax.swing.JTextField();
        textFieldJednostkaAmplitudy1 = new javax.swing.JTextField();
        textFieldMaxJednostkaAmplitudy1 = new javax.swing.JTextField();
        sliderMaxAmplituda1 = new javax.swing.JSlider();
        buttonWystrzalCyfrowa = new javax.swing.JButton();
        scrollPanePosrednieCyfrowa = new javax.swing.JScrollPane();
        textAreaPosrednieCyfrowa = new javax.swing.JTextArea();
        scrollPaneSegmentyCyfrowa = new javax.swing.JScrollPane();
        listSegmentyCyfrowa = new javax.swing.JList<>();
        labelJednostki2 = new javax.swing.JLabel();
        labelWynik1 = new javax.swing.JLabel();
        labelJednostki3 = new javax.swing.JLabel();
        labelPosrednie1 = new javax.swing.JLabel();
        labelSegment1 = new javax.swing.JLabel();
        labelAmplituda1 = new javax.swing.JLabel();
        labelMaxAmplituda1 = new javax.swing.JLabel();
        textFieldWynikCyfrowa = new javax.swing.JTextField();
        sliderAmplituda1 = new javax.swing.JSlider();
        textFieldWynik12Bitowy = new javax.swing.JTextField();
        labelWynik12Bitowy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tele PT Suite Pro 2000 Extended");

        panel13Segmentowa.setBorder(javax.swing.BorderFactory.createTitledBorder("Kompresja wg char. 13 segmentowej"));

        labelAmplituda0.setText("Amplituda Sygnału");

        labelMaxAmplituda0.setText("Amplituda Maksymalna");

        textFieldAmplituda0.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldAmplituda0.setText("6.25");
        textFieldAmplituda0.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldAmplituda0.setMargin(new java.awt.Insets(2, 2, 2, 2));

        textFieldMaxAmplituda0.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldMaxAmplituda0.setText("12.5");
        textFieldMaxAmplituda0.setMargin(new java.awt.Insets(2, 2, 2, 2));

        textFieldJednostkaAmplitudy0.setText("V");
        textFieldJednostkaAmplitudy0.setMargin(new java.awt.Insets(2, 2, 2, 2));

        textFieldMaxJednostkaAmplitudy0.setText("V");
        textFieldMaxJednostkaAmplitudy0.setMargin(new java.awt.Insets(2, 2, 2, 2));

        labelJednostki0.setText("[V, mV]");

        labelJednostki1.setText("[V, mV]");

        textFieldWynik13Segmentowa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textFieldWynik13Segmentowa.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldWynik13Segmentowa.setText("11101111");
        textFieldWynik13Segmentowa.setMargin(new java.awt.Insets(2, 2, 2, 2));

        sliderAmplituda0.setMinorTickSpacing(10);
        sliderAmplituda0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderAmplituda0.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAmplituda0StateChanged(evt);
            }
        });

        sliderMaxAmplituda0.setMinorTickSpacing(10);
        sliderMaxAmplituda0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderMaxAmplituda0.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMaxAmplituda0StateChanged(evt);
            }
        });

        labelWynik0.setText("Wynik:");

        buttonWystrzal13Segmentowa.setText("Wystrzał");
        buttonWystrzal13Segmentowa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWystrzal13SegmentowaActionPerformed(evt);
            }
        });

        textAreaPosrednie13Segmentowa.setColumns(20);
        textAreaPosrednie13Segmentowa.setRows(5);
        textAreaPosrednie13Segmentowa.setMargin(new java.awt.Insets(2, 2, 2, 2));
        scrollPanePosrednie13Segmentowa.setViewportView(textAreaPosrednie13Segmentowa);

        labelPosrednie0.setText("Wyniki pośrednie");

        listSegmenty13Segmentowa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Segment 1", "Segment 2", "Segment 3", "Segment 4", "Segment 5", "Segment 6", "Segment 7", "Segment 8" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listSegmenty13Segmentowa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listSegmenty13Segmentowa.setToolTipText("");
        scrollPaneSegmenty13Segmentowa.setViewportView(listSegmenty13Segmentowa);

        labelSegment0.setText("Segment:");

        javax.swing.GroupLayout panel13SegmentowaLayout = new javax.swing.GroupLayout(panel13Segmentowa);
        panel13Segmentowa.setLayout(panel13SegmentowaLayout);
        panel13SegmentowaLayout.setHorizontalGroup(
            panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                        .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelMaxAmplituda0)
                            .addComponent(labelAmplituda0)
                            .addComponent(labelWynik0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldMaxAmplituda0)
                                    .addComponent(textFieldAmplituda0, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldMaxJednostkaAmplitudy0)
                                    .addComponent(textFieldJednostkaAmplitudy0, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(textFieldWynik13Segmentowa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelPosrednie0)
                    .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(scrollPanePosrednie13Segmentowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel13SegmentowaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                                .addComponent(labelSegment0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPaneSegmenty13Segmentowa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonWystrzal13Segmentowa)))
                    .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                        .addComponent(labelJednostki0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderAmplituda0, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                    .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                        .addComponent(labelJednostki1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderMaxAmplituda0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel13SegmentowaLayout.setVerticalGroup(
            panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAmplituda0)
                        .addComponent(textFieldAmplituda0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldJednostkaAmplitudy0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelJednostki0))
                    .addComponent(sliderAmplituda0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMaxAmplituda0)
                        .addComponent(textFieldMaxAmplituda0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldMaxJednostkaAmplitudy0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelJednostki1))
                    .addComponent(sliderMaxAmplituda0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldWynik13Segmentowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWynik0))
                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                        .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSegment0)
                            .addComponent(scrollPaneSegmenty13Segmentowa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(buttonWystrzal13Segmentowa))
                    .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelPosrednie0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPanePosrednie13Segmentowa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        tab13Segmentowa.addTab("13 Segmentowa", panel13Segmentowa);

        panelCyfrowa.setBorder(javax.swing.BorderFactory.createTitledBorder("Kompresja cyfrowa (12b -> 8b)"));

        textFieldAmplituda1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldAmplituda1.setText("0.0");
        textFieldAmplituda1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldAmplituda1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        textFieldMaxAmplituda1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldMaxAmplituda1.setText("0.0");
        textFieldMaxAmplituda1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        textFieldJednostkaAmplitudy1.setText("V");
        textFieldJednostkaAmplitudy1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        textFieldMaxJednostkaAmplitudy1.setText("V");
        textFieldMaxJednostkaAmplitudy1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        sliderMaxAmplituda1.setMinorTickSpacing(10);
        sliderMaxAmplituda1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonWystrzalCyfrowa.setText("Wystrzał");

        textAreaPosrednieCyfrowa.setColumns(20);
        textAreaPosrednieCyfrowa.setRows(5);
        textAreaPosrednieCyfrowa.setMargin(new java.awt.Insets(2, 2, 2, 2));
        scrollPanePosrednieCyfrowa.setViewportView(textAreaPosrednieCyfrowa);

        listSegmentyCyfrowa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Segment 1a", "Segment 1b", "Segment 2", "Segment 3", "Segment 4", "Segment 5", "Segment 6", "Segment 7" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listSegmentyCyfrowa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listSegmentyCyfrowa.setToolTipText("");
        scrollPaneSegmentyCyfrowa.setViewportView(listSegmentyCyfrowa);

        labelJednostki2.setText("[V, mV]");

        labelWynik1.setText("Wynik:");

        labelJednostki3.setText("[V, mV]");

        labelPosrednie1.setText("Wyniki pośrednie");

        labelSegment1.setText("Segment:");

        labelAmplituda1.setText("Amplituda Sygnału");

        labelMaxAmplituda1.setText("Amplituda Maksymalna");

        textFieldWynikCyfrowa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textFieldWynikCyfrowa.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldWynikCyfrowa.setText("00000000");
        textFieldWynikCyfrowa.setMargin(new java.awt.Insets(2, 2, 2, 2));

        sliderAmplituda1.setMinorTickSpacing(10);
        sliderAmplituda1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        textFieldWynik12Bitowy.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldWynik12Bitowy.setText("000000000000");

        labelWynik12Bitowy.setText("Wynik 12 bitowy:");

        javax.swing.GroupLayout panelCyfrowaLayout = new javax.swing.GroupLayout(panelCyfrowa);
        panelCyfrowa.setLayout(panelCyfrowaLayout);
        panelCyfrowaLayout.setHorizontalGroup(
            panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCyfrowaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCyfrowaLayout.createSequentialGroup()
                        .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAmplituda1)
                            .addComponent(labelMaxAmplituda1)
                            .addComponent(labelWynik1)
                            .addComponent(labelWynik12Bitowy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldWynik12Bitowy, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCyfrowaLayout.createSequentialGroup()
                                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldAmplituda1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldMaxAmplituda1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldJednostkaAmplitudy1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldMaxJednostkaAmplitudy1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(textFieldWynikCyfrowa, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelCyfrowaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(scrollPanePosrednieCyfrowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelPosrednie1))
                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCyfrowaLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(buttonWystrzalCyfrowa))
                    .addGroup(panelCyfrowaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCyfrowaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelSegment1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPaneSegmentyCyfrowa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCyfrowaLayout.createSequentialGroup()
                                .addComponent(labelJednostki2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderAmplituda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelCyfrowaLayout.createSequentialGroup()
                                .addComponent(labelJednostki3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderMaxAmplituda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelCyfrowaLayout.setVerticalGroup(
            panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCyfrowaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAmplituda1)
                        .addComponent(textFieldAmplituda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldJednostkaAmplitudy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelJednostki2))
                    .addComponent(sliderAmplituda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMaxAmplituda1)
                        .addComponent(textFieldMaxAmplituda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldMaxJednostkaAmplitudy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelJednostki3))
                    .addComponent(sliderMaxAmplituda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldWynikCyfrowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWynik1))
                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCyfrowaLayout.createSequentialGroup()
                        .addComponent(scrollPaneSegmentyCyfrowa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonWystrzalCyfrowa))
                    .addGroup(panelCyfrowaLayout.createSequentialGroup()
                        .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSegment1)
                            .addGroup(panelCyfrowaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFieldWynik12Bitowy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelWynik12Bitowy))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPosrednie1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPanePosrednieCyfrowa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        tab13Segmentowa.addTab("Cyfrowa", panelCyfrowa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab13Segmentowa)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab13Segmentowa)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonWystrzal13SegmentowaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWystrzal13SegmentowaActionPerformed

        double amplit = 0;
        double maxAmplit = 0;
        try {
            amplit = Double.parseDouble(textFieldAmplituda0.getText());
            maxAmplit = Double.parseDouble(textFieldMaxAmplituda0.getText());
        } catch (IllegalArgumentException | NullPointerException e) {
            System.out.println("Error in parsing double!"); //TODO Error handling
        }
        
        amplituda.setAmplituda(amplit, textFieldJednostkaAmplitudy0.getText());
        amplituda.setMaxAmplituda(maxAmplit, textFieldMaxJednostkaAmplitudy0.getText());
        textAreaPosrednie13Segmentowa.setText("");
        textAreaPosrednie13Segmentowa.append("Segment:  ".concat(amplituda.segmentowaPrzypiszSegment().toString()).concat("\n"));
        textAreaPosrednie13Segmentowa.append("Segm. binarnie:  ".concat(amplituda.segmentowaPrzypiszSegmentBinarnie()).concat("\n"));
        textAreaPosrednie13Segmentowa.append("Pozostałe 4 bity:  ".concat(amplituda.segmentowaGenerujPozostale4Bity()).concat("\n"));
        
        textFieldWynik13Segmentowa.setText(amplituda.segmentowaWyswietlKod());
        
        listSegmenty13Segmentowa.setSelectedIndex(amplituda.segmentowaPrzypiszSegment().ordinal());
    }//GEN-LAST:event_buttonWystrzal13SegmentowaActionPerformed

    private void sliderAmplituda0StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAmplituda0StateChanged
        
        double a, b;
        a = 0;
        try {
            a = Double.parseDouble(textFieldMaxAmplituda0.getText());
        } catch (IllegalArgumentException | NullPointerException e) {
            System.out.println("Error in parsing double!");
        }
        b = sliderAmplituda0.getValue() / 100.0 * a;
        textFieldAmplituda0.setText(String.valueOf(Round.round(b, 2)));
    }//GEN-LAST:event_sliderAmplituda0StateChanged

    private void sliderMaxAmplituda0StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMaxAmplituda0StateChanged

        double a, b;
        a = sliderMaxAmplituda0.getValue() * 0.25;
        textFieldMaxAmplituda0.setText(String.valueOf(Round.round(a, 2)));
        b = sliderAmplituda0.getValue() / 100.0 * a;
        textFieldAmplituda0.setText(String.valueOf(Round.round(b, 2)));
    }//GEN-LAST:event_sliderMaxAmplituda0StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ApplicationMainGUI().setVisible(true);
        });
    }
//<editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonWystrzal13Segmentowa;
    private javax.swing.JButton buttonWystrzalCyfrowa;
    private javax.swing.JLabel labelAmplituda0;
    private javax.swing.JLabel labelAmplituda1;
    private javax.swing.JLabel labelJednostki0;
    private javax.swing.JLabel labelJednostki1;
    private javax.swing.JLabel labelJednostki2;
    private javax.swing.JLabel labelJednostki3;
    private javax.swing.JLabel labelMaxAmplituda0;
    private javax.swing.JLabel labelMaxAmplituda1;
    private javax.swing.JLabel labelPosrednie0;
    private javax.swing.JLabel labelPosrednie1;
    private javax.swing.JLabel labelSegment0;
    private javax.swing.JLabel labelSegment1;
    private javax.swing.JLabel labelWynik0;
    private javax.swing.JLabel labelWynik1;
    private javax.swing.JLabel labelWynik12Bitowy;
    private javax.swing.JList<String> listSegmenty13Segmentowa;
    private javax.swing.JList<String> listSegmentyCyfrowa;
    private javax.swing.JPanel panel13Segmentowa;
    private javax.swing.JPanel panelCyfrowa;
    private javax.swing.JScrollPane scrollPanePosrednie13Segmentowa;
    private javax.swing.JScrollPane scrollPanePosrednieCyfrowa;
    private javax.swing.JScrollPane scrollPaneSegmenty13Segmentowa;
    private javax.swing.JScrollPane scrollPaneSegmentyCyfrowa;
    private javax.swing.JSlider sliderAmplituda0;
    private javax.swing.JSlider sliderAmplituda1;
    private javax.swing.JSlider sliderMaxAmplituda0;
    private javax.swing.JSlider sliderMaxAmplituda1;
    private javax.swing.JTabbedPane tab13Segmentowa;
    private javax.swing.JTextArea textAreaPosrednie13Segmentowa;
    private javax.swing.JTextArea textAreaPosrednieCyfrowa;
    private javax.swing.JTextField textFieldAmplituda0;
    private javax.swing.JTextField textFieldAmplituda1;
    private javax.swing.JTextField textFieldJednostkaAmplitudy0;
    private javax.swing.JTextField textFieldJednostkaAmplitudy1;
    private javax.swing.JTextField textFieldMaxAmplituda0;
    private javax.swing.JTextField textFieldMaxAmplituda1;
    private javax.swing.JTextField textFieldMaxJednostkaAmplitudy0;
    private javax.swing.JTextField textFieldMaxJednostkaAmplitudy1;
    private javax.swing.JTextField textFieldWynik12Bitowy;
    private javax.swing.JTextField textFieldWynik13Segmentowa;
    private javax.swing.JTextField textFieldWynikCyfrowa;
    // End of variables declaration//GEN-END:variables
// </editor-fold>

}
