//<editor-fold defaultstate="collapsed" desc="Copyright">
/*
 * Copyright (C) 2016 Błażej Sewera (Jazz)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//</editor-fold>
package mainPackage;

/**
 * @author Błażej Sewera (Jazz)
 * @version 0.9 (2016-06-28)
 */
public class ApplicationMainGUI extends javax.swing.JFrame {

    private final Amplituda amplituda;
    
    {
        amplituda = new Amplituda();
    }

    /**
     * Creates new form ApplicationMainGUI
     */
    public ApplicationMainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupAddR = new javax.swing.JPopupMenu();
        itemAddR0 = new javax.swing.JMenuItem();
        itemAddR1 = new javax.swing.JMenuItem();
        popupAddC = new javax.swing.JPopupMenu();
        itemAddC0 = new javax.swing.JMenuItem();
        itemAddC1 = new javax.swing.JMenuItem();
        tabbedPaneMain = new javax.swing.JTabbedPane();
        panel13Segmentowa = new javax.swing.JPanel();
        labelAmplituda0 = new javax.swing.JLabel();
        labelMaxAmplituda0 = new javax.swing.JLabel();
        textFieldAmplituda0 = new javax.swing.JTextField();
        textFieldMaxAmplituda0 = new javax.swing.JTextField();
        textFieldWynik13Segmentowa = new javax.swing.JTextField();
        sliderAmplituda0 = new javax.swing.JSlider();
        sliderMaxAmplituda0 = new javax.swing.JSlider();
        labelWynik0 = new javax.swing.JLabel();
        buttonWystrzal13Segmentowa = new javax.swing.JButton();
        scrollPanePosrednie13Segmentowa = new javax.swing.JScrollPane();
        textAreaPosrednie13Segmentowa = new javax.swing.JTextArea();
        labelPosrednie0 = new javax.swing.JLabel();
        scrollPaneSegmenty13Segmentowa = new javax.swing.JScrollPane();
        listSegmenty13Segmentowa = new javax.swing.JList<>();
        labelSegment0 = new javax.swing.JLabel();
        panelCyfrowa = new javax.swing.JPanel();
        textFieldAmplituda1 = new javax.swing.JTextField();
        textFieldMaxAmplituda1 = new javax.swing.JTextField();
        sliderMaxAmplituda1 = new javax.swing.JSlider();
        buttonWystrzalCyfrowa = new javax.swing.JButton();
        scrollPanePosrednieCyfrowa = new javax.swing.JScrollPane();
        textAreaPosrednieCyfrowa = new javax.swing.JTextArea();
        scrollPaneSegmentyCyfrowa = new javax.swing.JScrollPane();
        listSegmentyCyfrowa = new javax.swing.JList<>();
        labelWynik1 = new javax.swing.JLabel();
        labelPosrednie1 = new javax.swing.JLabel();
        labelSegment1 = new javax.swing.JLabel();
        labelAmplituda1 = new javax.swing.JLabel();
        labelMaxAmplituda1 = new javax.swing.JLabel();
        textFieldWynikCyfrowa = new javax.swing.JTextField();
        sliderAmplituda1 = new javax.swing.JSlider();
        textFieldWynik12Bitowy = new javax.swing.JTextField();
        labelWynik12Bitowy = new javax.swing.JLabel();
        panelDC = new javax.swing.JPanel();
        labelR0 = new javax.swing.JLabel();
        textFieldR0 = new javax.swing.JTextField();
        toggleSzereg0 = new javax.swing.JToggleButton();
        buttonAddR = new javax.swing.JButton();
        labelR1 = new javax.swing.JLabel();
        textFieldR1 = new javax.swing.JTextField();
        labelC0 = new javax.swing.JLabel();
        labelC1 = new javax.swing.JLabel();
        textFieldC0 = new javax.swing.JTextField();
        textFieldC1 = new javax.swing.JTextField();
        toggleSzereg1 = new javax.swing.JToggleButton();
        buttonAddC = new javax.swing.JButton();

        itemAddR0.setText("prosty");
        popupAddR.add(itemAddR0);

        itemAddR1.setText("zaawansowany");
        popupAddR.add(itemAddR1);

        itemAddC0.setText("prosty");
        popupAddC.add(itemAddC0);

        itemAddC1.setText("zaawansowany");
        popupAddC.add(itemAddC1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tele PT Suite Pro 2000 Extended");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panel13Segmentowa.setBorder(javax.swing.BorderFactory.createTitledBorder("Kompresja wg char. 13 segmentowej"));

        labelAmplituda0.setText("Amplituda Sygnału");

        labelMaxAmplituda0.setText("Amplituda Maksymalna");

        textFieldAmplituda0.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldAmplituda0.setText("6.25");
        textFieldAmplituda0.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldAmplituda0.setMargin(new java.awt.Insets(2, 2, 2, 2));

        textFieldMaxAmplituda0.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldMaxAmplituda0.setText("12.5");
        textFieldMaxAmplituda0.setMargin(new java.awt.Insets(2, 2, 2, 2));

        textFieldWynik13Segmentowa.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textFieldWynik13Segmentowa.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldWynik13Segmentowa.setText("11101111");
        textFieldWynik13Segmentowa.setMargin(new java.awt.Insets(2, 2, 2, 2));

        sliderAmplituda0.setMinorTickSpacing(10);
        sliderAmplituda0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderAmplituda0.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAmplituda0StateChanged(evt);
            }
        });

        sliderMaxAmplituda0.setMinorTickSpacing(10);
        sliderMaxAmplituda0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderMaxAmplituda0.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMaxAmplituda0StateChanged(evt);
            }
        });

        labelWynik0.setText("Wynik:");

        buttonWystrzal13Segmentowa.setText("Wystrzał");
        buttonWystrzal13Segmentowa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWystrzal13SegmentowaActionPerformed(evt);
            }
        });

        textAreaPosrednie13Segmentowa.setColumns(20);
        textAreaPosrednie13Segmentowa.setRows(5);
        textAreaPosrednie13Segmentowa.setMargin(new java.awt.Insets(2, 2, 2, 2));
        scrollPanePosrednie13Segmentowa.setViewportView(textAreaPosrednie13Segmentowa);

        labelPosrednie0.setText("Wyniki pośrednie");

        listSegmenty13Segmentowa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Segment 1", "Segment 2", "Segment 3", "Segment 4", "Segment 5", "Segment 6", "Segment 7", "Segment 8" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listSegmenty13Segmentowa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listSegmenty13Segmentowa.setToolTipText("");
        scrollPaneSegmenty13Segmentowa.setViewportView(listSegmenty13Segmentowa);

        labelSegment0.setText("Segment:");

        javax.swing.GroupLayout panel13SegmentowaLayout = new javax.swing.GroupLayout(panel13Segmentowa);
        panel13Segmentowa.setLayout(panel13SegmentowaLayout);
        panel13SegmentowaLayout.setHorizontalGroup(
            panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                        .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelMaxAmplituda0)
                            .addComponent(labelAmplituda0)
                            .addComponent(labelWynik0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldWynik13Segmentowa, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textFieldMaxAmplituda0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(textFieldAmplituda0, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(labelPosrednie0)
                    .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(scrollPanePosrednie13Segmentowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel13SegmentowaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonWystrzal13Segmentowa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel13SegmentowaLayout.createSequentialGroup()
                                .addComponent(labelSegment0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPaneSegmenty13Segmentowa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(sliderAmplituda0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(sliderMaxAmplituda0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel13SegmentowaLayout.setVerticalGroup(
            panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAmplituda0)
                        .addComponent(textFieldAmplituda0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderAmplituda0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMaxAmplituda0)
                        .addComponent(textFieldMaxAmplituda0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderMaxAmplituda0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldWynik13Segmentowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelWynik0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPosrednie0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPanePosrednie13Segmentowa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel13SegmentowaLayout.createSequentialGroup()
                        .addGap(0, 108, Short.MAX_VALUE)
                        .addGroup(panel13SegmentowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneSegmenty13Segmentowa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSegment0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonWystrzal13Segmentowa)))
                .addGap(15, 15, 15))
        );

        tabbedPaneMain.addTab("13 Segmentowa", panel13Segmentowa);

        panelCyfrowa.setBorder(javax.swing.BorderFactory.createTitledBorder("Kompresja cyfrowa (12b -> 8b)"));

        textFieldAmplituda1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldAmplituda1.setText("6.25");
        textFieldAmplituda1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldAmplituda1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        textFieldMaxAmplituda1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldMaxAmplituda1.setText("12.5");
        textFieldMaxAmplituda1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        sliderMaxAmplituda1.setMinorTickSpacing(10);
        sliderMaxAmplituda1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderMaxAmplituda1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMaxAmplituda1StateChanged(evt);
            }
        });

        buttonWystrzalCyfrowa.setText("Wystrzał");
        buttonWystrzalCyfrowa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWystrzalCyfrowaActionPerformed(evt);
            }
        });

        textAreaPosrednieCyfrowa.setColumns(20);
        textAreaPosrednieCyfrowa.setRows(5);
        textAreaPosrednieCyfrowa.setMargin(new java.awt.Insets(2, 2, 2, 2));
        scrollPanePosrednieCyfrowa.setViewportView(textAreaPosrednieCyfrowa);

        listSegmentyCyfrowa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Segment 1a", "Segment 1b", "Segment 2", "Segment 3", "Segment 4", "Segment 5", "Segment 6", "Segment 7" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listSegmentyCyfrowa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listSegmentyCyfrowa.setToolTipText("");
        scrollPaneSegmentyCyfrowa.setViewportView(listSegmentyCyfrowa);

        labelWynik1.setText("Wynik:");

        labelPosrednie1.setText("Wyniki pośrednie");

        labelSegment1.setText("Segment:");

        labelAmplituda1.setText("Amplituda Sygnału");

        labelMaxAmplituda1.setText("Amplituda Maksymalna");

        textFieldWynikCyfrowa.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textFieldWynikCyfrowa.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldWynikCyfrowa.setText("00000000");
        textFieldWynikCyfrowa.setMargin(new java.awt.Insets(2, 2, 2, 2));

        sliderAmplituda1.setMinorTickSpacing(10);
        sliderAmplituda1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderAmplituda1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAmplituda1StateChanged(evt);
            }
        });

        textFieldWynik12Bitowy.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textFieldWynik12Bitowy.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldWynik12Bitowy.setText("000000000000");

        labelWynik12Bitowy.setText("Wynik 12 bitowy:");

        javax.swing.GroupLayout panelCyfrowaLayout = new javax.swing.GroupLayout(panelCyfrowa);
        panelCyfrowa.setLayout(panelCyfrowaLayout);
        panelCyfrowaLayout.setHorizontalGroup(
            panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCyfrowaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCyfrowaLayout.createSequentialGroup()
                        .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAmplituda1)
                            .addComponent(labelMaxAmplituda1)
                            .addComponent(labelWynik1)
                            .addComponent(labelWynik12Bitowy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldWynik12Bitowy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textFieldMaxAmplituda1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(textFieldAmplituda1, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(textFieldWynikCyfrowa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCyfrowaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(scrollPanePosrednieCyfrowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelPosrednie1))
                .addGap(18, 18, 18)
                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCyfrowaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonWystrzalCyfrowa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCyfrowaLayout.createSequentialGroup()
                                .addComponent(labelSegment1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPaneSegmentyCyfrowa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(sliderAmplituda1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(sliderMaxAmplituda1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCyfrowaLayout.setVerticalGroup(
            panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCyfrowaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAmplituda1)
                        .addComponent(textFieldAmplituda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderAmplituda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMaxAmplituda1)
                        .addComponent(textFieldMaxAmplituda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderMaxAmplituda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCyfrowaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldWynikCyfrowa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelWynik1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldWynik12Bitowy, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelWynik12Bitowy))
                        .addGap(18, 80, Short.MAX_VALUE)
                        .addComponent(labelPosrednie1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPanePosrednieCyfrowa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCyfrowaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelCyfrowaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneSegmentyCyfrowa, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSegment1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonWystrzalCyfrowa)))
                .addGap(15, 15, 15))
        );

        tabbedPaneMain.addTab("Cyfrowa", panelCyfrowa);

        labelR0.setText("R0:");

        textFieldR0.setToolTipText("");

        toggleSzereg0.setText("szeregowo");
        toggleSzereg0.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                toggleSzereg0ItemStateChanged(evt);
            }
        });

        buttonAddR.setText("+");
        buttonAddR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddRActionPerformed(evt);
            }
        });

        labelR1.setText("R1:");

        textFieldR1.setToolTipText("");

        labelC0.setText("C0:");

        labelC1.setText("C1:");

        textFieldC0.setToolTipText("");

        textFieldC1.setToolTipText("");

        toggleSzereg1.setText("szeregowo");
        toggleSzereg1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                toggleSzereg1ItemStateChanged(evt);
            }
        });

        buttonAddC.setText("+");
        buttonAddC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDCLayout = new javax.swing.GroupLayout(panelDC);
        panelDC.setLayout(panelDCLayout);
        panelDCLayout.setHorizontalGroup(
            panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDCLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAddR))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDCLayout.createSequentialGroup()
                        .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelR0)
                            .addGroup(panelDCLayout.createSequentialGroup()
                                .addComponent(textFieldR0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toggleSzereg0, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelC0)
                            .addGroup(panelDCLayout.createSequentialGroup()
                                .addComponent(textFieldC0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toggleSzereg1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDCLayout.createSequentialGroup()
                                .addComponent(labelC1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                                .addComponent(buttonAddC))
                            .addGroup(panelDCLayout.createSequentialGroup()
                                .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldR1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelR1)
                                    .addComponent(textFieldC1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelDCLayout.setVerticalGroup(
            panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAddR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelR0)
                    .addComponent(labelR1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldR0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleSzereg0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(buttonAddC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelC0)
                    .addComponent(labelC1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldC0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleSzereg1))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        tabbedPaneMain.addTab("Obwód prądu stałego", panelDC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonWystrzal13SegmentowaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWystrzal13SegmentowaActionPerformed

        double amplit = 0;
        double maxAmplit = 0;
        try {
            amplit = Double.parseDouble(textFieldAmplituda0.getText());
            maxAmplit = Double.parseDouble(textFieldMaxAmplituda0.getText());
        } catch (IllegalArgumentException | NullPointerException e) {
            System.out.println("Error in parsing double (Segmentowa)!"); //TODO Error handling
        }
        
        amplituda.setAmplituda(amplit, "V");
        amplituda.setMaxAmplituda(maxAmplit, "V");
        textAreaPosrednie13Segmentowa.setText("");
        textAreaPosrednie13Segmentowa.append("Segment:  ".concat(amplituda.segmentowaPrzypiszSegment().toString()).concat("\n"));
        textAreaPosrednie13Segmentowa.append("Segm. binarnie:  ".concat(amplituda.segmentowaPrzypiszSegmentBinarnie()).concat("\n"));
        textAreaPosrednie13Segmentowa.append("Pozostałe 4 bity:  ".concat(amplituda.segmentowaGenerujPozostale4Bity()).concat("\n"));
        
        textFieldWynik13Segmentowa.setText(amplituda.segmentowaWyswietlKod());
        
        listSegmenty13Segmentowa.setSelectedIndex(amplituda.segmentowaPrzypiszSegment().ordinal());
    }//GEN-LAST:event_buttonWystrzal13SegmentowaActionPerformed

    private void sliderAmplituda0StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAmplituda0StateChanged
        
        double a, b;
        a = 0;
        try {
            a = Double.parseDouble(textFieldMaxAmplituda0.getText());
        } catch (IllegalArgumentException | NullPointerException e) {
            System.out.println("Error in parsing double!");
        }
        b = sliderAmplituda0.getValue() / 100.0 * a;
        textFieldAmplituda0.setText(String.valueOf(Round.round(b, 2)));
    }//GEN-LAST:event_sliderAmplituda0StateChanged

    private void sliderMaxAmplituda0StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMaxAmplituda0StateChanged

        double a, b;
        a = sliderMaxAmplituda0.getValue() * 0.25;
        textFieldMaxAmplituda0.setText(String.valueOf(Round.round(a, 2)));
        b = sliderAmplituda0.getValue() / 100.0 * a;
        textFieldAmplituda0.setText(String.valueOf(Round.round(b, 2)));
    }//GEN-LAST:event_sliderMaxAmplituda0StateChanged

    private void buttonWystrzalCyfrowaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWystrzalCyfrowaActionPerformed
        
        double amplit = 0;
        double maxAmplit = 0;
        try {
            amplit = Double.parseDouble(textFieldAmplituda1.getText());
            maxAmplit = Double.parseDouble(textFieldMaxAmplituda1.getText());
        } catch (IllegalArgumentException | NullPointerException e) {
            System.out.println("Error in parsing double (Cyfrowa)!"); //TODO Error handling
        }
        
        amplituda.setMaxAmplituda(maxAmplit, "V");
        amplituda.setAmplituda(amplit, "V");
        textAreaPosrednieCyfrowa.setText("");
        textAreaPosrednieCyfrowa.append("Segment:  ".concat(amplituda.cyfrowaPrzypiszSegment().toString()).concat("\n"));
        textAreaPosrednieCyfrowa.append("Segm. binarnie:  ".concat(amplituda.cyfrowaPrzypiszSegmentBinarnie()).concat("\n"));
        textAreaPosrednieCyfrowa.append("Pozostałe 4 bity:  ".concat(amplituda.cyfrowaGenerujPozostale4Bity()).concat("\n"));
        
        textFieldWynik12Bitowy.setText(amplituda.cyfrowaGeneruj12Bitowy());
        textFieldWynikCyfrowa.setText(amplituda.cyfrowaWyswietlKod());
        
        listSegmentyCyfrowa.setSelectedIndex(amplituda.cyfrowaPrzypiszSegment().ordinal());
        
        /*        System.out.print("Cyfrowa:\n\n"
        .concat(String.valueOf(amplit)).concat(" = ").concat(String.valueOf(amplituda.getAmplituda())).concat("\n")
        .concat(String.valueOf(maxAmplit)).concat(" = ").concat(String.valueOf(amplituda.getMaxAmplituda())).concat("\n")
        .concat("Segment:  ".concat(amplituda.cyfrowaPrzypiszSegment().toString()).concat("\n"))
        .concat("Segm. binarnie:  ".concat(amplituda.cyfrowaPrzypiszSegmentBinarnie()).concat("\n"))
        .concat("Pozostałe 4 bity:  ".concat(amplituda.cyfrowaGenerujPozostale4Bity()).concat("\n"))
        .concat("12 Bitowy:   ".concat(amplituda.cyfrowaGeneruj12Bitowy()).concat("\n"))
        .concat("Wynik:   ".concat(amplituda.cyfrowaWyswietlKod()).concat("\n"))
        .concat("----------------------".concat("\n"))
        );*/
    }//GEN-LAST:event_buttonWystrzalCyfrowaActionPerformed

    private void sliderAmplituda1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAmplituda1StateChanged
        
        double a, b;
        a = 0;
        try {
            a = Double.parseDouble(textFieldMaxAmplituda1.getText());
        } catch (IllegalArgumentException | NullPointerException e) {
            System.out.println("Error in parsing double!");
        }
        b = sliderAmplituda1.getValue() / 100.0 * a;
        textFieldAmplituda1.setText(String.valueOf(Round.round(b, 2)));
    }//GEN-LAST:event_sliderAmplituda1StateChanged

    private void sliderMaxAmplituda1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMaxAmplituda1StateChanged

        double a, b;
        a = sliderMaxAmplituda1.getValue() * 0.25;
        textFieldMaxAmplituda1.setText(String.valueOf(Round.round(a, 2)));
        b = sliderAmplituda1.getValue() / 100.0 * a;
        textFieldAmplituda1.setText(String.valueOf(Round.round(b, 2)));
    }//GEN-LAST:event_sliderMaxAmplituda1StateChanged

    private void toggleSzereg0ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_toggleSzereg0ItemStateChanged
        if (toggleSzereg0.getText().equals("szeregowo"))
            toggleSzereg0.setText("równolegle");
        else
            toggleSzereg0.setText("szeregowo");
    }//GEN-LAST:event_toggleSzereg0ItemStateChanged

    private void toggleSzereg1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_toggleSzereg1ItemStateChanged
        if (toggleSzereg1.getText().equals("szeregowo"))
            toggleSzereg1.setText("równolegle");
        else
            toggleSzereg1.setText("szeregowo");
    }//GEN-LAST:event_toggleSzereg1ItemStateChanged

    private void buttonAddRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddRActionPerformed
        
        popupAddR.show(this, buttonAddR.getX(), buttonAddR.getY());
    }//GEN-LAST:event_buttonAddRActionPerformed

    private void buttonAddCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddCActionPerformed
        
        popupAddC.show(this, buttonAddC.getX(), buttonAddC.getY());
    }//GEN-LAST:event_buttonAddCActionPerformed


//<editor-fold defaultstate="collapsed" desc="Main (commented)">
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ApplicationMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new ApplicationMainGUI().setVisible(true);
//        });
//    }
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddC;
    private javax.swing.JButton buttonAddR;
    private javax.swing.JButton buttonWystrzal13Segmentowa;
    private javax.swing.JButton buttonWystrzalCyfrowa;
    private javax.swing.JMenuItem itemAddC0;
    private javax.swing.JMenuItem itemAddC1;
    private javax.swing.JMenuItem itemAddR0;
    private javax.swing.JMenuItem itemAddR1;
    private javax.swing.JLabel labelAmplituda0;
    private javax.swing.JLabel labelAmplituda1;
    private javax.swing.JLabel labelC0;
    private javax.swing.JLabel labelC1;
    private javax.swing.JLabel labelMaxAmplituda0;
    private javax.swing.JLabel labelMaxAmplituda1;
    private javax.swing.JLabel labelPosrednie0;
    private javax.swing.JLabel labelPosrednie1;
    private javax.swing.JLabel labelR0;
    private javax.swing.JLabel labelR1;
    private javax.swing.JLabel labelSegment0;
    private javax.swing.JLabel labelSegment1;
    private javax.swing.JLabel labelWynik0;
    private javax.swing.JLabel labelWynik1;
    private javax.swing.JLabel labelWynik12Bitowy;
    private javax.swing.JList<String> listSegmenty13Segmentowa;
    private javax.swing.JList<String> listSegmentyCyfrowa;
    private javax.swing.JPanel panel13Segmentowa;
    private javax.swing.JPanel panelCyfrowa;
    private javax.swing.JPanel panelDC;
    private javax.swing.JPopupMenu popupAddC;
    private javax.swing.JPopupMenu popupAddR;
    private javax.swing.JScrollPane scrollPanePosrednie13Segmentowa;
    private javax.swing.JScrollPane scrollPanePosrednieCyfrowa;
    private javax.swing.JScrollPane scrollPaneSegmenty13Segmentowa;
    private javax.swing.JScrollPane scrollPaneSegmentyCyfrowa;
    private javax.swing.JSlider sliderAmplituda0;
    private javax.swing.JSlider sliderAmplituda1;
    private javax.swing.JSlider sliderMaxAmplituda0;
    private javax.swing.JSlider sliderMaxAmplituda1;
    private javax.swing.JTabbedPane tabbedPaneMain;
    private javax.swing.JTextArea textAreaPosrednie13Segmentowa;
    private javax.swing.JTextArea textAreaPosrednieCyfrowa;
    private javax.swing.JTextField textFieldAmplituda0;
    private javax.swing.JTextField textFieldAmplituda1;
    private javax.swing.JTextField textFieldC0;
    private javax.swing.JTextField textFieldC1;
    private javax.swing.JTextField textFieldMaxAmplituda0;
    private javax.swing.JTextField textFieldMaxAmplituda1;
    private javax.swing.JTextField textFieldR0;
    private javax.swing.JTextField textFieldR1;
    private javax.swing.JTextField textFieldWynik12Bitowy;
    private javax.swing.JTextField textFieldWynik13Segmentowa;
    private javax.swing.JTextField textFieldWynikCyfrowa;
    private javax.swing.JToggleButton toggleSzereg0;
    private javax.swing.JToggleButton toggleSzereg1;
    // End of variables declaration//GEN-END:variables
// </editor-fold>

}
